apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: eks-redis
data:
  redis.conf: |
    port 6379
    bind 0.0.0.0
    dir /data
    appendonly yes
    maxmemory 256mb
    maxmemory-policy allkeys-lru
