name: Deploy Devops-project

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: Manual Run
        required: false
        type: string
        
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:

  build:

   runs-on: ubuntu-latest

   steps:

    - uses: actions/checkout@v4



    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
           version: 2                         # default
           verbose: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: eu-central-1

    - name: Intalling kubectl
      run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mv ./kubectl /usr/local/bin

    - name: Install Curl 
      run: |
          sudo apt-get update -y && sudo apt-get install curl

    - name: Install terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init and plan
      id: plan
      run: |
         cd ./module   # Directory where the Terraform files are present
         terraform init && terraform plan

    - name: Terraform apply
      id: Apply
      run: |
         cd ./module
         terraform apply --auto-approve


         # Deploy Redis

    - name: Verify AWS Credentials
      run: aws sts get-caller-identity
 
    - name: Set up kubectl
      run: |
           aws eks update-kubeconfig --name devops-cluster --region eu-central-1
           kubectl version --client
           kubectl get nodes
 
    - name: Deploy Redis
      run: |
           kubectl apply -f redis/     # Applying entire redis folder
 
    - name: Verify Deployment
      run: |
           kubectl rollout status statefulset redis -n eks-redis
           kubectl get pods -n eks-redis
           #kubectl exec -it redis-0 -n eks-redis -- /bin/bash -c "curl -v http://redis.eks-redis.svc.cluster.local:6379"
