name: Destroy Devops-project

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: Manual Run
        required: false
        type: string
        
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:

  build:

   runs-on: ubuntu-latest

   steps:

    - uses: actions/checkout@v4



    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
           version: 2                         # default
           verbose: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: eu-central-1

    - name: Intalling kubectl
      run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mv ./kubectl /usr/local/bin

    - name: Install terraform
      uses: hashicorp/setup-terraform@v3

#    - name: Delete workflow for Redis
#      id: plan
#      run: |
#         kubectl delete -f redis/*.yml
         

    - name: Terraform destroy
      id: Destroy
      run: |
         cd ./module
         terraform init && terraform destroy --auto-approve
